---@class AlomawaniQoL : table
---@field System System
---@field Interface Interface
---@field Gameplay Gameplay
---@field L table<string, string>
---@field AlomawaniQoLGui AlomawaniQoLGui
---@field Print fun(...: any) Print text in chat
---@field Debug fun(...: any) Print text in chat if Debug is enabled
---@field addonName string
---@field colorRGB number[]
---@field colorHex string
---@field pretty string

---@class AlomawaniQoLConfigs
---@field Debug boolean
---@field MaxOutCameraDistance boolean
---@field UsePerfectPixel boolean
---@field UseCustomHeight string
---@field MuteAnnoyingSound boolean
---@field DisableChatClamping boolean
---@field DisableRightClickTargeting boolean
---@field FasterAutoLoot boolean
---@field AddVoiceLineWhenDead boolean
---@field PrintQuoteFromThichNhatHanh boolean
---@field KeepABattlePetSummoned boolean
---@field BattlePetNameToSummon string
---@field RepairGearAutomatically boolean
---@field UseGuildBankForRepair boolean
---@field SellJunkAutomatically boolean
---@field DisableDamageText boolean
---@field HideTooltipWhileInCombat boolean
---@field HidePlayerPortraitWhenHeal boolean
---@field ObjectiveTrackerScale number

---@class AlomawaniQoLData
---@field Configs AlomawaniQoLConfigs
